StartBootstrap-2-ASP/Models/Settings.cs
using System.ComponentModel.DataAnnotations;

namespace StartBootstrap_2_ASP.Models
{
    public class Settings
    {
        [Key]
        public int Id { get; set; }



        [MaxLength(50)]
        public string Logo { get; set; }



        [MaxLength(20)]
        public string BannerHeader { get; set; }




        [MaxLength(100)]
        public string BannerText { get; set; }

    }

}

StartBootstrap-2-ASP/Areas/admin/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using StartBootstrap_2_ASP.Data;
using StartBootstrap_2_ASP.Models;
using System.Linq;

namespace StartBootstrap_2_ASP.Areas.admin.Controllers
{
    [Area("admin")]
    public class SettingsController : Controller
    {
        private readonly AppDbContext _context;

        public SettingsController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.settings.FirstOrDefault());
        }


        public IActionResult Update()
        {
            return View(_context.settings.FirstOrDefault());
        }


        [HttpPost]
        public IActionResult Update(Settings model)
        {
            if (ModelState.IsValid)
            {
                _context.settings.Update(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
    }
}

StartBootstrap-2-ASP/Areas/admin/Views/Settings/Index.cshtml
@model Settings


<div class="container-fluid">
	<h2 class="mb-3">Settings</h2>
	<table class="table">
		<thead>
			<tr>
				<th scope="col">Logo</th>
				<th scope="col">BannerHeader</th>
				<th scope="col">BannerText</th>
				<th scope="col">Modify</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>@Model.Logo</td>
				<td>@Model.BannerHeader</td>
				<td>@Model.BannerText</td>
				<td>
					<a class="btn btn-primary" asp-area="admin" asp-controller="Settings" asp-action="Update">Update</a>
				</td>
			</tr>
		</tbody>
	</table>
</div>

StartBootstrap-2-ASP/Areas/admin/Views/Settings/Update.cshtml
@model Settings


<div class="container-fluid">
	<h2 class="mb-5">Update Settings</h2>
	<form class="w-50" asp-area="admin" asp-controller="Settings" asp-action="Update" method="post">
		<div class="mb-3">
			<label asp-for="@Model.Logo" class="form-label">Category Name</label>
			<input class="form-control" asp-for="@Model.Logo">
		</div>
		<div class="mb-3">
			<label asp-for="@Model.BannerHeader" class="form-label">Category Name</label>
			<input class="form-control" asp-for="@Model.BannerHeader">
		</div>
		<div class="mb-3">
			<label asp-for="@Model.BannerText" class="form-label">Category Name</label>
			<input class="form-control" asp-for="@Model.BannerText">
		</div>
		<input asp-for = "@Model.Id" hidden />
		<button type="submit" class="btn btn-primary">Update</button>
	</form>
</div>